name = "Fastback"
uuid = "cac590ea-fc37-4aa9-92e2-88b1ae187e30"
authors = ["Rino Beeli <rino.beeli@gmail.com>"]
version = "1.0.0"
repo = "https://github.com/rbeeli/fastback.jl.git"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
